### ISSUE TITLE
.p-heading-icons images are misaligned when using large `h` elements

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#2505] opened 2019-08-20 14:49 UTC
**Describe the bug**
`.p-heading-icon` doesn't accommodate `<h1>` or `<h2>` elements, leading to misaligned icons.

**To Reproduce**
1. Go to https://codepen.io/sowasred2012/pen/LYPRvVR

**Expected behavior**
The docs don't explicitly call out that the pattern only works with `<h3>` elements, so I had expected the pattern to work with any heading element - which is not the case.

**Screenshots**
- h1:
![Screenshot 2019-08-20 at 15 32 43](https://user-images.githubusercontent.com/2376968/63357754-d851e300-c361-11e9-8789-6de99c0f9d75.png)

- h2:
![Screenshot 2019-08-20 at 15 33 38](https://user-images.githubusercontent.com/2376968/63357798-f1f32a80-c361-11e9-908a-90252773d2a1.png)

**Comment by lyubomir-popov** [comment] 2020-10-14 10:26
So the problem is we can't target an element preceding an element with a css selector. So we either need a class on the img like "for-h1" or we need to change the order of the markup  (img ibnside heading, or img following a heading) so that a selectoer can target it.

**Comment by bartaz** [comment] 2021-03-15 10:57
Will be addressed by canonical-web-and-design/vanilla-framework#3376

**Closed by bartaz** 2021-03-15 10:57 UTC
Labels: Priority: Medium
