### ISSUE TITLE
.p-link--inverted doesn't stand out when next to text

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/vanilla-framework#2622] opened 2019-11-05 14:14 UTC
## Pattern to amend

[Inverted link](https://docs.vanillaframework.io/patterns/links/)

## Visual
The inverted link doesn't stand out much when it's part of a paragraph. Looks worst on non-retina screens.

![Screenshot 2019-11-05 at 14 10 45](https://user-images.githubusercontent.com/36884067/68214864-1f04c000-ffd6-11e9-8159-99b6ddebcd6d.png)

## Context

As a quick (and maybe temporary) solution we made the link `style="font-style: italic;"`.

![Screenshot 2019-11-05 at 14 10 15](https://user-images.githubusercontent.com/36884067/68215117-9c303500-ffd6-11e9-8cff-dd053bd1b738.png)

Would be nice to explore other solutions and update this on vanilla.

**Comment by lyubomir-popov** [comment] 2019-11-05 14:56
This looks like increase emphasis. If it is meant to look like a link, why not just reinstate the underline?

**Comment by anasereijo** [comment] 2019-11-05 16:05
> This looks like increase emphasis. If it is meant to look like a link, why not just reinstate the underline?

We tried that actually. Should this be on vanilla?

**Comment by kwm14** [comment] 2019-11-07 10:22
> This looks like increase emphasis. If it is meant to look like a link, why not just reinstate the underline?

Previously links had an underline by default which made them more visible, but Mark wasn't keen so we introduced our default blue but kept the underline on hover.

But happy to discuss further in WG meeting 👍

**Comment by matthewpaulthomas** [comment] 2019-11-07 12:58
This is an unfortunate combination of one factor in the use case…
- It would be quite difficult to style “the new standard for embedded Linux”, as the only styled text in a paragraph, in any way that made it obviously a link rather than a slogan. All the page’s other sub-pages are linked later in the page instead. Perhaps embedded Linux could be too?

…And four factors in Vanilla:
- The archetypal formatting for links is blue (or some other vibrant colour), underlined, or both. `.p-link--inverted` uses neither, so it needs to work much harder to be obvious.
- The colour used is `#f7f7f7` vs. `#ffffff`, which is only 3.1% difference in shade and zero difference in hue.
- The style used is `font-weight: 400` vs. `300`, which is a very small difference at 16px even when unhinted on a retina display (and [_zero_ difference](https://github.com/canonical-web-and-design/vanilla-framework/issues/2272#issuecomment-482950827) when hinted on a non-retina display).
- Even if either of those differences was noticeable alone, the effects of slightly _brighter_ text from the bold, and slightly _dimmer_ text from the grey, basically cancel each other out!

I suggest using a lighter shade of Vanilla’s usual blue (something like `#6bbddb`), and a bolder weight.

**Comment by lyubomir-popov** [comment] 2019-11-19 16:46
An example from apple's [guidelines ](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/#darkmode-colors) in support of adjusting our colours when used on a dark background:

"Semantic colors (like labelColor and controlColor) adapt to the current appearance automatically."
![image](https://user-images.githubusercontent.com/2741678/69166799-bcd6af80-0aeb-11ea-9165-fa67c73919e5.png)

**Comment by matthewpaulthomas** [comment] 2020-01-09 11:31
> I suggest using a lighter shade of Vanilla’s usual blue (something like `#6bbddb`), and a bolder weight.

I just discovered that @MadsRH on the Yaru team has taken a similar approach with the Ubiquity slideshow, where there are links on an aubergine background. He’s currently using `#2ab7eb` for these links.

![image](https://user-images.githubusercontent.com/19801137/72064058-fdc09880-32d2-11ea-8ff6-7c2645f96294.png)

**Comment by spencerbygraves** [comment] 2020-01-09 14:59
I find the blue in the example above clashes with the orange to aubergine gradient, and starts to fizz or agitate my eye (not sure what you call that). I wonder if we can find a shade of blue that is visible on all of our backgrounds and gradients, and doesn't clash.

It may be easier to make the inverted link underlined for that reason, especially when it appears in a paragraph of text.

**Comment by kwm14** [comment] 2020-01-09 15:12
Agree with @spencerbygraves points. In terms of accessibility, it passes on Canonical mid aubergine `#5E2750` for WCAG AA using small or large text.

But unfortunately on Ubuntu orange `#E95420`, it fails across the board. It would need to be a darker shade to pass accessibility, which predominantly would be `#000000`

**Comment by madsrh** [comment] 2020-01-09 15:56
>  It would need to be a darker shade to pass accessibility, which predominantly would be #000000

IMHO `#000000` really isn't an option.

![image](https://user-images.githubusercontent.com/3986894/72082190-ab45a300-32f7-11ea-9b3a-f91a349ac34b.png)


If the text is white, perhaps just something close to white but different enough that you can tell that it's a link. 50% transparent of `#007aa6` will be `#7fbcd2` like below: 

![image](https://user-images.githubusercontent.com/3986894/72082490-24dd9100-32f8-11ea-8fdc-9c9a217565ef.png)

**Comment by matthewpaulthomas** [comment] 2020-01-09 16:06
Vanilla sites put text against a variety of background colours, not just aubergine and orange: [dark blue](https://kubeflow-news.com/), [turquoise](https://snapcraft.io/), [black](https://microk8s.io/), etc. And it’s trivially true that no link colour could possibly have enough contrast against every possible background colour. So we could:
- stop providing a link class that implies it can do this, and instead remind designers to choose a custom link colour whenever they set a custom background colour (something which Web designers have long experience of doing anyway!)
- use something other than colour for inverted links (for example, `.p-link--inverted {color: inherit; font-weight: bold; text-decoration: underline;}`).

**Comment by spencerbygraves** [comment] 2020-01-10 09:44
>use something other than colour for inverted links (for example, .p-link--inverted {color: inherit; font-weight: bold; text-decoration: underline;}).

Sounds good I think.

**Comment by spencerbygraves** [comment] 2020-01-27 14:13
WG: agreed we will try @matthewpaulthomas' suggestion and approve the design from there.

**Comment by lyubomir-popov** [comment] 2020-10-15 08:39
From the accesibility audit I believe :link colour should have 3:1 contrast against adjacent text. [Source](https://webaim.org/blog/wcag-2-0-and-link-colors/)

**Comment by lyubomir-popov** [comment] 2020-10-15 08:40
![Uploading image.png…]()

**Comment by bartaz** [comment] 2021-03-15 11:15
Duplicate of canonical-web-and-design/vanilla-framework#3350

Addressing issues with inverted link would be a breaking change, so it's postponed for now.

**Closed by bartaz** 2021-03-15 11:15 UTC
Labels: Priority: Medium, WG: Validated
