### ISSUE TITLE
Proposed pattern: Graphs and charts 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/vanilla-framework#3111] opened 2020-06-04 15:35 UTC
There are lots of great graphs and charts on snapcraft.io - we should define a common (at least UX/visual) pattern across all our products

**Comment by SirSamTumless** [comment] 2020-06-05 08:31
#2305

**Comment by lyubomir-popov** [comment] 2020-06-05 08:42
There are plans to create a separate chart library, but the work for that is not scheduled to take place this cycle. Closing as it is a duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/2305

**Closed by lyubomir-popov** 2020-06-05 08:42 UTC
