### ISSUE TITLE
Option to hide the tabs arrow on mobile

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3172] opened 2020-07-16 09:55 UTC
## Pattern to amend

p-tabs

## Visual

![image](https://user-images.githubusercontent.com/40214246/87657350-a0f6dc80-c752-11ea-9ea7-a765de36844f.png)

## Context

When using `p-tabs` there should be an option not to show the chevron on mobile when you only have a few tabs

**Comment by solazio** [comment] 2020-07-21 15:52
In that case maybe we can re-evaluate if we need that arrow or there is something else we can use. But worst thing it can still be "manually" hidden on the specific page if not needed.

**Comment by lyubomir-popov** [comment] 2020-07-21 16:01
Wondering if it would be better to have the arrow as an option rather than a default. 
In case of overflow, usually one tab would be half visible, plus a horisontal scrollbar will appear, so there would still be affordances that the thing is scrollable.

**Comment by anthonydillon** [comment] 2020-07-21 16:08
It would not be possible to be sure we are not cutting off items and there are no scroll bars on phones.

**Comment by bartaz** [comment] 2021-03-15 12:10
Duplicate of canonical-web-and-design/vanilla-framework#3602

**Closed by bartaz** 2021-03-15 12:10 UTC
Labels: Priority: Low
