### ISSUE TITLE
Code block scroll view on long snippets unreadable

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2695] opened 2019-12-06 13:46 UTC
_Reported by @lilyvidenova_ 

## Pattern to amend

[Code block 
](https://docs.vanillaframework.io/base/code/#block)

## Visual

Link of an example in a recent [blog post](https://ubuntu.com/blog/hardware-discovery-and-kernel-auto-configuration-in-maas) by MAAS engineer.
<img width="499" alt="Screenshot 2019-12-06 at 12 55 27" src="https://user-images.githubusercontent.com/17748020/70324612-dc7a1180-1827-11ea-8548-360d8b8a292d.png">

## Context

Currently, if a snippet is longer than the input's defined width it turns into a scrollable view, which can cause issues:
- Snippet not visible
- Ability to copy the snippet
- Visibility of the snippet as the scrollbar overlays

**Comment by spencerbygraves** [comment] 2020-01-27 14:00
@deadlight is going to discuss with @lilyvidenova and update this issue.

**Comment by lyubomir-popov** [comment] 2020-04-20 12:54
Duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/2457, closing.

**Closed by lyubomir-popov** 2020-04-20 12:54 UTC
Labels: WG: Proposal
