### ISSUE TITLE
Command line pattern, styled with “$” prompt

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#1549] opened 2018-01-30 01:21 UTC
It’s common for guides to technical software to include commands to enter at a terminal.

For example, on “[Build on LXD or Docker](https://docs.snapcraft.io/build-snaps/build-on-lxd-docker)”:
> First, install LXD:
>```
> sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
> sudo apt update
> sudo apt install lxd
> sudo lxd init
>```

One of our snapcraft.io prototype testers saw similar instructions, and pointed out that it’s usual for terminal commands to be written with a `$` at the start, imitating the terminal prompt. This also helps distinguish between input and output.

We already do this in other places. For example, in “[Build your first snap](https://docs.snapcraft.io/build-snaps/your-first-snap)”:
> The `--dangerous` flag needs to be used here because your snap has not been signed.
>```
> $ sudo snap install hello_2.10_*.snap --dangerous
> hello 2.10 installed
>```
> Congratulations, you’ve just made and installed your first snap!
>
> You can run the `hello` command to see it in action:
>```
> $ hello
> Hello, World!
>```
Unfortunately, if you copy either of those commands, it is easy to copy the `$` symbols by mistake, resulting in an error. They are being included in the content when, really, they’re presentational.

Vanilla already solves this problem for something else presentational: [line numbers](https://docs.vanillaframework.io/en/patterns/code-numbered). You can happily copy the code without copying the line numbers by mistake.

Vanilla should have an equivalent way to identify the specific lines, inside a `<pre>`, which are terminal commands. As well as being omitted from copying, they could use a grey color (like Vanilla line numbers do) to avoid distracting from the command itself.

**Comment by deadlight** [comment] 2019-02-19 09:09
@matthewpaulthomas I will attempt to address this for larger code blocks but some of your single-line examples would correctly be styled with a $ (and have an optional copy button) if they used the [code snippet](https://docs.vanillaframework.io/en/patterns/code-snippet) pattern, which is more suited for this purpose.

**Comment by deadlight** [comment] 2019-02-19 09:30
On further investigation, there's no way to modify the current markup used for code blocks to include a styling element for adding non-copyable $ to specific lines (i.e., Selectively adding $s for input and no $s for output).

I think this marks the limitation of the current component and we should move to a more complex and flexible component.

**Comment by matthewpaulthomas** [comment] 2019-02-20 08:57
That surprises me. In Firefox’s Web Inspector I stuck a `<div>` between those two Livepatch commands above, then tweaked the CSS a bit, and got pretty close to what I’m proposing.

Code:
```html
<pre class="p-code-numbered"><code>
<span class="code-line">sudo snap install canonical-livepatch</span>
<div>Example output</div>
<span class="code-line">sudo canonical-livepatch enable 37…</span>
</code></pre>
```
Result:
![vanilla-framework 1549-test](https://user-images.githubusercontent.com/19801137/53078444-89cba500-34f4-11e9-89c9-e135b0d614c8.png)

It wouldn’t be a great choice of markup to use `<span class="code-line">` for input and `<div>` for output. But we could get the same effect from, say, `<div class="input">` and `<div>`.

**Comment by deadlight** [comment] 2019-02-20 09:49
@matthewpaulthomas it turns out that I was misinformed about the permitted contents of a <pre> tag - it is permitted to contain any [phrasing content elements](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) which would include <spans>. I will have a look at this again, I should be able to copy the styling of the code snippet component's $ fairly easily.

It's worth noting that the <div> in your example would be invalid markup, however, just in case that's a real-world example.

**Comment by deadlight** [comment] 2019-02-22 09:17
Rather than fixing this bug in-situ, I've suggested restructuring the component to make using this component a better experience that covers more of our use cases: #2170

**Comment by wgx** [comment] 2020-12-01 16:37
Addressed by "Command prompt" in spec: https://discourse.ubuntu.com/t/code-snippet-pattern/19195#command-prompt

**Comment by wgx** [comment] 2020-12-01 16:38
Duplicate of #2170

**Closed** 2020-12-01 16:38 UTC
Labels: Priority: Medium
