### ISSUE TITLE
Justify buttons in rows

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#2463] opened 2019-08-09 04:19 UTC
The buttons in a table row are helpfully narrower, but possibly they should also move up a bit to not make the row larger than normal text content. See this comment: https://app.zeplin.io/project/5ce5423a25863c1e0d7abb27/screen/5d36e2233615fbb2789ce87f (the relevant bit being: "Please note the icons will need to have some negative margin-top and bottom in order to not "swell" tds.they need to overlap the .25rem td padding.")

In MAAS I've resolved this with:

```css
td:not(.p-table-expanding__panel) [class*="p-button"] {
  margin-top: -0.25rem;
  margin-bottom: -0.25rem;
}
```

**Comment by lyubomir-popov** [comment] 2019-09-18 08:10
This is a duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/2504, or viceversa. Seems to me we need a utility to negate the default td padding that can be applied to anything.

**Comment by lyubomir-popov** [comment] 2019-11-08 11:23
What the above snippet is doing is allowing a child element to "overlap" the padding of table rows. This can be useful in many contexts, e.g. if you want to place a paragraph instead of relying on the row to keep text from touching its borders. I propose wrapping it in a utility, something like "u-overlap-table-row-padding". Unless @deadlight can come up with a better name?

**Closed** 2019-11-14 20:51 UTC
Labels: Priority: Low
