### ISSUE TITLE
Checkbox opacity set to 0 when to the right of label

### ISSUE THREAD

**Issue by jpmartinspt** [canonical-web-and-design/vanilla-framework#2009] opened 2018-10-01 16:36 UTC
Whenever a checkbox input is added after the label, it's opacity is set to 0, making it invisible.
In following example the checkbox is invisible.

`
<label>Sad</label>
<input type="checkbox" name="">
`

**Comment by barrymcgee** [comment] 2018-10-08 14:18
## Expected

You should be able to add a `<label>` before a `<input type="checkbox">` without it becoming invisible. 

## Action needed

Amend Sass to ensure this is not the case. 

Starting point: The base form styling: https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_base_forms.scss

**Comment by kwm14** [comment] 2019-05-21 11:22
Did you manage to fix this issue @jpmartinspt based on @barrymcgee feedback?

**Comment by lyubomir-popov** [comment] 2019-05-21 11:29
@kwm14 I can confirm this hasn't been fixed. We style the checkbox using pseudo elements on the label, so having the label follow the checkbox in the markup is important (unless anyone has a better implementation?).

I would suggest a variant that swaps the order of the rendered label and checkbox, while maintaining the order in the markup unchanged.

**Comment by jpmartinspt** [comment] 2019-05-22 09:58
@kwm14 I think I fixed it in whatever project I was working on back then, just raised the issue so it could be fixed in vanilla. If you guys think it's not relevant feel free to close.

**Comment by lyubomir-popov** [comment] 2019-05-22 10:07
@kwm14 @jpmartinspt fixing this requires adopting a different technique to style checkboxes / radios, e.g. with mandatory js. So maybe set this to blocked until an alternative is validated in the WG?

**Comment by lyubomir-popov** [comment] 2019-08-30 13:35
This is a duplicate of #1983.The core issue is that the semantic markup is not styleable in a consistent way across browsers. This is why we resort to the pseudo element hack. AFAIK the only alternative is to build a bespoke component with javascript like this one: https://material.io/develop/web/components/input-controls/checkboxes/
Would be good to make a decision if we want to go this route, as this bug is raised often.

**Comment by lyubomir-popov** [comment] 2019-09-02 15:52
CLosing as it is a duplicate of #1983. The pr fixing this will be connected to #1983 as agreed in the discussion there.

**Closed by lyubomir-popov** 2019-09-02 15:52 UTC
Labels: Priority: Medium
