### ISSUE TITLE
Spacing between a and button elements inconsistent 

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/vanilla-framework#2408] opened 2019-07-15 08:28 UTC
**Describe the bug**

The spacing between an `a` followed by a `button` is not consistent with the spacing between a `button` followed by a `button`.

**To Reproduce**
https://jsfiddle.net/4nwjm3g8/1/

**Expected behavior**
The elements should have the same spacing.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser: Chrome 75.0.3770.100 (Official Build) (64-bit)

Affects Vanilla 2.0.1+

**Comment by lyubomir-popov** [comment] 2020-10-14 10:21
Duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/1897

**Closed by lyubomir-popov** 2020-10-14 10:21 UTC
Labels: Duplicate, Priority: Medium
