### ISSUE TITLE
Responsive table labels take up too much size

### ISSUE THREAD

**Issue by aguadoenzo** [canonical-web-and-design/vanilla-framework#3598] opened 2021-03-01 16:06 UTC
**Describe the bug**

On mobile (tested on an iPhone X), table lables take up too much space and force elements on the right to be squashed

**To Reproduce**

Use a table with long elements on the right

**Expected behavior**

Labels should take less space to avoid the content to wrap and be aligned on the left
**Screenshots**
![image](https://user-images.githubusercontent.com/11411723/109523869-221b9d80-7ab0-11eb-9e7b-48b59a49b20c.png)

**Smartphone (please complete the following information):**

- Device: [iPhone X]
- OS: [iOS 14.4]
- Browser [safari]

**Comment by lyubomir-popov** [comment] 2021-03-01 16:40
This seems a duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/2817.

**Closed** 2021-03-02 09:30 UTC
