### ISSUE TITLE
Sortable table jumps when sorting

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/vanilla-framework#3488] opened 2021-01-12 14:10 UTC
When you use the sorting arrows, the [table jumps a little bit](https://vanillaframework.io/docs/examples/patterns/tables/table-sortable). This can also be seen on the [Jaas tables](https://jaas.ai/models).

**Comment by lyubomir-popov** [comment] 2021-01-12 14:13
Duplicate of [this](https://github.com/canonical-web-and-design/vanilla-framework/issues/3120) right @bartaz?

**Comment by bartaz** [comment] 2021-01-12 14:34
Fixed via #3120.

Thanks @spencerbygraves, we happened to fix this last week, so it will be released with next version of Vanilla.

**Closed by bartaz** 2021-01-12 14:34 UTC
