### ISSUE TITLE
Style the browsers default validation elements.

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3178] opened 2020-07-21 20:57 UTC
## Pattern to amend

Validation

## Visual

(In Firefox on macos)
![Screen Shot 2020-07-21 at 2 51 24 PM](https://user-images.githubusercontent.com/532033/88106098-27039080-cb62-11ea-9264-8f61bd403aac.png)

![Screen Shot 2020-07-21 at 2 56 33 PM](https://user-images.githubusercontent.com/532033/88106241-65994b00-cb62-11ea-8d1e-69e7714941de.png)

## Context

While we have our own implementation of form validation it would be nice if we could rely on the built-in browser handling of form validation and style appropriately using the [pseudo-classes](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#Using_built-in_form_validation)

**Comment by bartaz** [comment] 2020-07-22 08:40
There is a number of issues with native form validation.

- there is limited validation functinality (only checking for required, some specific types or regex patterns)
- there is no control over error messages - we can't define error message text or its styling
- there is no native way to show server-side error messages

To have control over error messages text (which is crucial to good UX) we need to support validation styling via class names and custom error messages. We can't get rid of this in favor of client-side native browser validation.

What we may try to do is, additionally to existing validation styles, have better support for native client-side validation. So when the field is using client-side validation it will for example use Vanilla error border when is `:invalid`.

**Comment by SirSamTumless** [comment] 2020-07-24 08:29
Going to be fixed by #2931

**Comment by bartaz** [comment] 2020-08-05 06:14
It's not going to be fixed by #2931 - while it is related, and having a checkbox pattern can improve positioning of validation tooltip on checkbox, it will not make native validation work out of the box with Vanilla forms in general, this is a separate issue.

**Comment by lyubomir-popov** [comment] 2020-10-16 09:02
- checkbox already fixed
- the rest is duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/3262

**Closed by lyubomir-popov** 2020-10-16 09:02 UTC
Labels: Feature 🎁
