### ISSUE TITLE
Placeholder should not replace label

### ISSUE THREAD

**Issue by marinacastejon** [canonical-web-and-design/vanilla-framework#4071] opened 2021-10-15 06:49 UTC
Placeholders replacing labels in certain input fields. 

In Vanilla there are 2 instances of this: 

- [Search and filter component](https://vanillaframework.io/docs/patterns/search-and-filter)
<img width="912" alt="Screenshot 2021-10-15 at 09 17 47" src="https://user-images.githubusercontent.com/83575/137447641-6cf4f734-c531-4f66-bebd-523185763eb8.png">

- [Search box component](https://vanillaframework.io/docs/patterns/search-box)
<img width="912" alt="Screenshot 2021-10-15 at 09 17 59" src="https://user-images.githubusercontent.com/83575/137447653-f23e7c6e-5bc7-4c51-8c0a-2af98a56b39f.png">

Summary of previous analysis:
- Placeholders cannot replace labels. If the visible label is removed there should be at least a hidden label so that screen readers read the label. 
- While there might be a workaround to make this accessible to screen reader users, there are mentions about this behaviour of the placeholder acting as label and then disappearing when clicking that indicate problems for people with cognitive disabilities. 

- [WCAG Placeholder text](https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text)
- [WCAG Labels](https://www.w3.org/WAI/tutorials/forms/labels/)
- [Deque](https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/#:~:text=In%20recent%20years%2C%20placeholders%20are,form%20field%20is%20referring%20to)
- [NNG](https://www.nngroup.com/articles/form-design-placeholders/)

It is worth mentioning that [W3C WAI](https://www.w3.org/WAI/) has a search box without a visible label and the placeholder disappears when typing. 
![image.png](https://images.zenhubusercontent.com/61309e789df65d8124887eac/996666a9-eca7-4d24-ab4e-09307c46c10d)

**Comment by bartaz** [comment] 2021-10-15 07:20
Thanks @marinacastejon, I think we should bring this to Working Group meeting and discuss there. Especially around making Search & Filter more clear, as that's the one that doesn't have the button with search icon.

**Comment by clagom** [comment] 2021-11-03 10:38
WG: double check if for screen readers this is well implemented. CC @bartaz

**Comment by marinacastejon** [comment] 2021-11-03 10:50
Blocked until checked with users with cognitive disabilities. I'll try to find participants in Canonical for the research on the hiring dashboards.

**Comment by marinacastejon** [comment] 2022-02-07 11:21
It doesn't look like I will be able to recruit any participants with Aspergers or autism spectrum. Therefore, I investigated and tried to find some research that explicitly said advised against the use of placeholders as labels.
- What we already knew, [NNGroup advises against that](https://www.nngroup.com/articles/form-design-placeholders/), but doesn't mention any sources. 
> Users with cognitive or motor impairments are more heavily burdened.  As we saw, placeholders can be problematic for all users: disappearing placeholders increase the memory load; persistent dimmable placeholders cause confusion when they look clickable but aren’t, and placeholders that do not disappear require more keyboard or mouse interaction to be deleted. These difficulties are magnified for people with cognitive or motor impairments.

Other sources I checked. I found nothing regarding placeholders replacing labels and disappearing on users input. 
- [Cognitive user research from W3C](https://w3c.github.io/coga/user-research/). 
- Research gate paper: [User Interface for People with Autism Spectrum Disorders](https://www.researchgate.net/publication/276495184_User_Interface_for_People_with_Autism_Spectrum_Disorders)
- [National Autism Society](https://www.autism.org.uk/)

I suspect it is not the best practice but there is no solid evidence showing that this is blocking users. Since NNG does not point to any sources and WCAG cognitive working group does not mention it. 
I think we can close this issue @bartaz @clagom

**Comment by clagom** [comment] 2022-02-09 10:25
WG: the accessibility guild is going to discuss this during the accessibility working group. @bethcollins92

**Comment by bethcollins92** [comment] 2022-02-17 14:46
@marinacastejon

I've added labels to all the searchbox examples on Vanilla since this issue was created. I haven't checked all our websites, but everyone in the accessibility guild is now aware we need labels and not just placeholders, so they will check their projects and add them if necessary

**Comment by davegoddard42** [comment] 2022-04-05 21:25
I asked the design team to [try and find any input fields](https://miro.com/app/board/uXjVOHYZffE=/?invite_link_id=853117013314) within our sites and products that lacked a label - every example was a search box. The [Vanilla guidelines](https://vanillaframework.io/docs/base/forms) state that input fields consist of a text input and a label. This appears to be adhered to, and the issue is confined purely to search and search & filter patterns, as @marinacastejon  mentioned. 

As Marina also found from research, there doesn’t seem to be a “smoking gun” showing that using placeholder text for labels specifically on a search input is bad for people with cognitive accessibilities. There is however, evidence that using placeholder text for labels on input form fields does increase cognitive load, which in particular impacts those with cognitive disabilities (https://youtu.be/xjPqwsRIq7E?t=602). 

A lack of a label does cause issues for screen readers but this has been addressed by @bethcollins92's work outlined above.

**Does a search box need a label?**

Nielsen Norman Group state that the main guidelines (https://www.nngroup.com/articles/search-visible-and-simple/) for search boxes are as follows:

* Provide an easily identifiable search box in the upper right-hand corner of the page, with an open text-field accompanied by a Search button.
* The search box needs no label. A Search button next to the field identifies the search for the user and tells them how to execute the search.

There are occasions when text fields may not need a label as "_the purpose may be clear enough from the context when the content is rendered visually_" ([Web Accessibility Initiative](https://www.w3.org/WAI/tutorials/forms/labels/)). 

It can be argued that the search button (Shown in Vanilla as a magnifying glass) acts as a label. As a very widely used pattern across the web ([NN Group](https://www.nngroup.com/articles/magnifying-glass-icon/?lm=search-visible-and-simple&pt=article)), the magnifying glass next to an open text field is well understood by most users.

**Cognitive load and the impact on those with cognitive disabilities**

The problem with using placeholder text to label a field in general is that it increases the cognitive load for a user, and this can be especially problematic for users with cognitive disabilities ([Designing for Cognitive Disabilities axe con 2022](https://youtu.be/xjPqwsRIq7E?t=602)). 

The increase in cognitive load comes from: 
- If user loses attention, they might not remember what they’re being asked
- Can’t easily check answer before submitting because the user doesn’t know what they’ve answered. 
- Can’t correct errors easily
- May mistake placeholder data as filled in
- Filled fields are less noticeable 

**In pages with multiple fields, the problem is magnified**

The search and search & filter components differ from normal text fields that might make it the exception. 
- It is one field only, not multiple
- There are no errors or need to check the correct input - searches that return no results explain how to get better results
- Users are unlikely to think that “Search” is what they had previously typed in

Norman Nielsen introduce the Search capability using the opening sentence “_Search lets users control their own destiny and assert independence from websites' attempt to direct how they use the web_”. It appears there is a difference between a form field and a search box - namely, a form fields represent an interface asking a user for an answer, and so what’s being asked for should be visible at all times for the issues around cognitive load outlined above. 

A search box however, is the user asking the interface a question - when the user interacts with the component they define what’s being input, and have the necessary context for the content. 

**Conclusion**

A input fields must have a label, and using placeholder text is not good enough. On the search input however, the magnifying glass acts as a label. The unique nature of the search interaction also means the usual issues around cognitive load are lessened. I'd argue there isn’t a need to add a label to the search component. 

In Vanilla, the [Search and Filter](https://vanillaframework.io/docs/patterns/search-and-filter) component lacks a magnifying glass icon. On typing in the field, the dropdown shows “Search for …”, giving context to the user.   Despite this, I’d suggest that the magnifying glass icon should be added to the pattern.

**Comment by clagom** [comment] 2022-04-06 09:44
WG: @davegoddard42 @marinacastejon (and @wgx from the other search-related issue) are going to review our search and filter spec and eventually amend/integrate it.

**Comment by clagom** [comment] 2022-06-15 09:07
@davegoddard42 is going to work on the spec, closing this issue.

**Closed by clagom** 2022-06-15 09:07 UTC
Labels: Priority: Medium, WG: Validated
