### ISSUE TITLE
Fieldset: Transparent border on fieldset results in border colour spilling outside element

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3424] opened 2020-11-23 11:59 UTC
**Describe the bug**

The transparent border currently applied to fieldsets causes a strange bug in chrome where the border color fills the window.

Replacing the fieldset with a div and copyign all fieldset styles onto the div doesn't seem to trigger the bug, so it seems highly specific to the fieldset or an inherent property of it:

![image](https://user-images.githubusercontent.com/2741678/99959134-60ebda00-2d82-11eb-81e1-5a5ae4cd1c2b.png)

**To Reproduce**

Paste this [markup](https://pastebin.canonical.com/p/2pnRKXPPkR/) in any site using vanilla.

- Device: Mac
- OS: Latest
- Browser Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by lyubomir-popov** [comment] 2020-11-23 12:01
The bug doesn't happen in safari and firefox on mac.

**Comment by lyubomir-popov** [comment] 2020-11-23 12:12
happens on some other markup elelments like input - if you keep the inline styles but change the div to input or fieldset (first div in the form element in the markup example above )

**Comment by bartaz** [comment] 2021-01-07 08:50
@lyubomir-popov Could you create a codepen or something with the example? I can't reproduce it by pasting your code.

**Comment by lyubomir-popov** [comment] 2021-01-07 08:57
@bartaz just tried it and I can't replicate in my current chrome version (last digits .88) either. Wonder if it was a browser bug in the version mentioned above. The only thing I can think of is checking the repo that reported it just before the fix I suggested was applied (the merge by Peter above).

**Comment by bartaz** [comment] 2021-01-07 09:14
Seems like it was fixed by Chrome. https://bugs.chromium.org/p/chromium/issues/detail?id=1150803

**Closed by bartaz** 2021-01-07 09:14 UTC
Labels: Bug 🐛, Priority: High
