### ISSUE TITLE
Contrast issues with hover in dark navigation

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2449] opened 2019-08-06 08:57 UTC
Default hover text color in navigation doesn't have enough contrast on dark background:
(see Forum on the screenshots:
<img width="737" alt="Screenshot 2019-08-06 at 10 08 44" src="https://user-images.githubusercontent.com/83575/62526022-b708d700-b838-11e9-8f4d-e9798aadae30.png">

**Expected behavior**
It should be possible to configure nav hover color to adapt it to custom background. Or hover colour should be more universal.
Especially that most of Canonical sites now use dark navigation.

**Comment by kwm14** [comment] 2019-08-06 09:10
Thanks for raising @bartaz 👍 

Small task to specify the exact hover-state color when using a dark background:

**Current behavior**
Using light navigation hover-state: `#757575`

**Expected behavior** 
Use `#9C9C9C` hover-state as discussed and signed off in [design issue](https://github.com/canonical-web-and-design/design-vanilla-framework/issues/208).

**Comment by therealjuan** [comment] 2019-08-06 14:18
I don't think this is just a simple problem with changing the colour to a light one because that makes the contrast between background and foreground un-accessible.

**Comment by kwm14** [comment] 2019-08-06 14:55
As I mentioned earlier the hover/selected color contrast was tested in design and passed WCAG 2 level AA contrast ratio of at least 4.5:1.

Hover/selected state for dark background `#9C9C9C`

**Vanilla colors**
- Background color `$color-x-dark` or `#000` - 7.6 contrat ratio - **PASS**
- Background color `$color-dark` or `#111` - 6.8 contrat ratio - **PASS**
- Background color `$color-brand` or `$color-brand` - 4.6 contrat ratio - **PASS**
  - Used in Snapcraft, JAAS, MAAS, Ubuntu, MicroK8s, Ubuntu China

**Comment by lyubomir-popov** [comment] 2019-08-23 09:10
Moving to in review as the theming spike hover color is adjusted for AA accessibility.

**Closed** 2019-09-02 13:38 UTC
Labels: Priority: Medium
