### ISSUE TITLE
Footer pattern

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2969] opened 2020-04-03 12:41 UTC
This is a suggestion to a footer pattern in vanilla that is always positioned at the bottom of the page, even the page content is minimal. What we currently use in general, is an extension of a strip with a custom style for each project. If there is not enough content on the page (depending on the display size), your footer ends up in the middle of the page instead of being at the bottom.

![image](https://user-images.githubusercontent.com/40214246/78361768-d535fb00-75b0-11ea-8b5e-f2bb82d863b8.png)

**Comment by bartaz** [comment] 2020-04-03 12:52
Seems duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/1452

@solazio Could you add you screenshot there as well, so we know another use case?

**Closed by bartaz** 2020-04-03 12:52 UTC
