### ISSUE TITLE
Improve when tooltips are shown/hidden

### ISSUE THREAD

**Issue by flamendless** [canonical-web-and-design/vanilla-framework#2833] opened 2020-02-17 04:41 UTC
**Describe the bug**
When a button with tooltip class is clicked, the tooltip box will not disappear unless another button is clicked.

**To Reproduce**
1. Go to the main example in the docs https://docs.vanillaframework.io/patterns/tooltips
2. Click on any button
3. Move the mouse out of the button
4. Click another button

**Expected behavior**
Tooltip should disappear upon mouse exiting the element (button)

**Comment by bartaz** [comment] 2020-02-17 12:32
@flamendless Thanks for reporting this.

I believe it's an expected behaviour, because we want tooltips to be visible both on hover and when element has focus. But I'll verify with designers if that's intended.

**Comment by bartaz** [comment] 2020-02-17 12:33
@lyubomir-popov Is it intended for the tooltips to stay open as long as element has focus?

**Comment by lyubomir-popov** [comment] 2020-02-17 12:40
@bartaz Yes, I believe so.

**Comment by flamendless** [comment] 2020-02-17 13:04
Really? I am unaware or have not encountered any thing like that so far. But I will trust what youve said as youre more knowledgeable. Thank you

**Comment by lyubomir-popov** [comment] 2020-02-17 14:05
Might be worth getting a UX opinion on this. @matthewpaulthomas, once displayed, should tooltips be visible until an element looses focus, or until a mouse moves away from it?

**Comment by bartaz** [comment] 2020-02-17 14:38
@flamendless Using focus to show tooltips help for example on mobile touch screens, where support for hover interactions is limited.

I'm closing this for now, but if you find any issues around this tooltip behaviour feel free to reopen it or report another issue.

Thanks for using Vanilla and taking time to report the issue.

**Comment by matthewpaulthomas** [comment] 2020-02-23 09:33
> we want tooltips to be visible both on hover and when element has focus

I understand that you want both, so that they can be accessible with a pointing device and with a keyboard. But this can’t possibly be desired behaviour:

![vanilla#2833-tooltips](https://user-images.githubusercontent.com/19801137/75109720-ff91b180-561d-11ea-94ed-f0799e71925e.png)

> @matthewpaulthomas, once displayed, should tooltips be visible until an element lo[]ses focus, or until a mouse moves away from it?

I think they should be visible until _either_ of those things happens, _or_ the element is clicked (which implies that you know enough to not need the tooltip any more).

That is, close a tooltip when any of these things happen:
- the pointer moves outside the control (the traditional trigger)
- the control is defocused
- the control is clicked (even if it remains focused afterwards).

**Comment by bartaz** [comment] 2020-02-24 12:47
This kind of behaviour would require keeping a state of the component and seems to be outside of we can do with just CSS.

We can try to provide a JS snippet for our example to implement this behaviour.

**Comment by matthewpaulthomas** [comment] 2020-02-25 09:05
> seems to be outside of we can do with just CSS

Absolutely, I don’t think it’s a good use of time trying to implement tooltips in CSS alone. Two more examples:
- A tooltip shouldn’t open on hover until you’ve hovered over the parent for ~1 second, so it doesn’t flicker distractingly if you pass over it on your way to something else. `title=` handles that, JS can handle that, but `:hover` can’t.
- When a tooltip is open, it should always be completely visible — which means choosing which direction to open depending on where the parent is on the display right now. `title=` handles that, JS can get close (albeit restricted by the viewport), but hard-coded `class="p-tooltip--btm-right"` etc can’t.

**Comment by lyubomir-popov** [comment] 2020-04-20 12:51
React version of tooltip should do this
Css version should aim to do as much as possible without js
Consider js example to replicate the functionality of the future react version

Consider in the ccontext of the info tip roadmap item [add link]

**Comment by bartaz** [comment] 2021-03-25 15:16
After canonical-web-and-design/vanilla-squad#1000 verify how much more is needed

**Closed** 2021-04-08 10:13 UTC
Labels: Priority: Medium, Review: Code needed, WG: Validated
