### ISSUE TITLE
Look at reducing the focus state on click

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3418] opened 2020-11-16 15:14 UTC
In a review, it was requested we look at reducing the focus state when you click a button or link. It is thought that the think blue border is garish.

**Comment by bartaz** [comment] 2020-11-19 14:57
We have a separate report to look into using :focus-visible - which makes focus visible when navigating with keyboard (when you expect it) but not visible when you click on things.
I guess it would help us keep prominent focus when needed, and avoid showing it when things are clicked. 

https://github.com/canonical-web-and-design/vanilla-framework/issues/3352

**Comment by bartaz** [comment] 2020-11-20 09:37
Closing as duplicate of #3352

**Closed by bartaz** 2020-11-20 09:37 UTC
